### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by Harshithasriniv** [lbechberger/ConceptualSpaces#2]
HI ,,
i got this attribute error to classify the test images.

from keras.preprocessing import image
img=image.load_img('data/test1/test images/01.jpg' , target_size=(178,218))
prediction=my_model.predict(img)
print (prediction)

any one please help me

AttributeError: 'Image' object has no attribute 'ndim'

**Comment by lbechberger** [comment]
I don't know what you are referring to. The ConceptualSpaces project does not do any image classification and also none of my other projects make use of keras. I guess this issue was opened in the wrong place.

**Comment by sushant097** [comment]
@Harshithasriniv Did you find the solution to resolve this issue?

**Comment by Harshithasriniv** [comment]
Hi ,
Yes,i found the solution.

**Comment by maazmunawer24** [comment]
what's the solution u got? @Harshithasriniv

**Comment by makki51x3** [comment]
According to the keras documentation , the [predict](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict
) function takes an ndarray as an input but you passed a PIL Image object returned by [image.load_img](https://www.tensorflow.org/api_docs/python/tf/keras/utils/img_to_array), solution:

- **Using keras**:
  1. Use image.img_to_array() function to convert the Image object to a numpy array
  2. Pass the array to the predict function
  
  ```
    from keras.preprocessing import image

    img=image.load_img('data/test1/test images/01.jpg' , target_size=(178,218))
    img_as_array = image.img_to_array(img)
    prediction=my_model.predict(img_as_array)

    print (prediction)
  ```
_OR_
- **Using numpy**:
  1. Import the numpy library
  2. Use numpy.array() function to convert the Image object to a numpy array
  3. Pass the array to the predict function
  
  ```
  import numpy as np 
  from keras.preprocessing import image

  img=image.load_img('data/test1/test images/01.jpg' , target_size=(178,218))
  img_as_array = np.array(img)
  prediction=my_model.predict(img_as_array )

  print (prediction)
  ```
